"""initial schema

Revision ID: aa880380da61
Revises: 
Create Date: 2026-08-02 02:23:38.491344
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'aa880380da61'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('company', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('onboarded', sa.Boolean(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('customers',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('company', sa.String(length=160), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tax_exempt', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_customers_org_name', 'customers', ['organization_id', 'name'], unique=False)
    op.create_table('machines',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('brand', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('heads', sa.Integer(), nullable=False),
    sa.Column('needle_count', sa.Integer(), nullable=False),
    sa.Column('hoop_width_mm', sa.Float(), nullable=False),
    sa.Column('hoop_height_mm', sa.Float(), nullable=False),
    sa.Column('max_stitch_count', sa.Integer(), nullable=False),
    sa.Column('max_speed_spm', sa.Integer(), nullable=False),
    sa.Column('supported_formats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('hourly_rate', sa.Float(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('connection', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memberships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'digitizer', 'operator', 'viewer', name='org_role'), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_membership')
    )
    op.create_table('products',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=True),
    sa.Column('fabric_profile', sa.String(length=40), nullable=False),
    sa.Column('color', sa.String(length=60), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=True),
    sa.Column('blank_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('reorder_level', sa.Integer(), nullable=False),
    sa.Column('supplier', sa.String(length=160), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'sku', name='uq_product_sku')
    )
    op.create_table('subscriptions',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Enum('free', 'pro', 'business', name='plan_tier'), nullable=False),
    sa.Column('status', sa.Enum('active', 'trialing', 'past_due', 'canceled', name='subscription_status'), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('provider_customer_id', sa.String(length=120), nullable=True),
    sa.Column('provider_subscription_id', sa.String(length=120), nullable=True),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id')
    )
    op.create_table('usage_events',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_org_period', 'usage_events', ['organization_id', 'occurred_at'], unique=False)
    op.create_table('designs',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'analyzing', 'vectorized', 'digitizing', 'ready', 'failed', 'archived', name='design_status'), nullable=False),
    sa.Column('source', sa.Enum('upload_image', 'upload_svg', 'upload_logo', 'ai_generated', 'text', name='design_source'), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('compatibility_score', sa.Integer(), nullable=True),
    sa.Column('stitch_count', sa.Integer(), nullable=True),
    sa.Column('color_count', sa.Integer(), nullable=True),
    sa.Column('width_mm', sa.Float(), nullable=True),
    sa.Column('height_mm', sa.Float(), nullable=True),
    sa.Column('trim_count', sa.Integer(), nullable=True),
    sa.Column('thread_length_m', sa.Float(), nullable=True),
    sa.Column('estimated_minutes', sa.Float(), nullable=True),
    sa.Column('thread_chart', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stitch_preview', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_designs_org_created', 'designs', ['organization_id', 'created_at'], unique=False)
    op.create_table('orders',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('quote', 'approved', 'digitizing', 'sewing', 'completed', 'delivered', 'cancelled', name='order_status'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('rush', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('placement', sa.String(length=80), nullable=True),
    sa.Column('assigned_machine_id', sa.UUID(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cost_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_machine_id'], ['machines.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'number', name='uq_order_number')
    )
    op.create_index('ix_orders_org_status', 'orders', ['organization_id', 'status'], unique=False)
    op.create_table('design_files',
    sa.Column('design_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('original', 'thumbnail', 'vector', 'preview', 'stitch', 'package', 'document', 'mockup', name='file_kind'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_files_design_kind', 'design_files', ['design_id', 'kind'], unique=False)
    op.create_table('embroidery_settings',
    sa.Column('design_id', sa.UUID(), nullable=False),
    sa.Column('fabric', sa.String(length=40), nullable=False),
    sa.Column('thread_catalog', sa.String(length=40), nullable=False),
    sa.Column('machine_id', sa.UUID(), nullable=True),
    sa.Column('target_width_mm', sa.Float(), nullable=True),
    sa.Column('target_height_mm', sa.Float(), nullable=True),
    sa.Column('fill_angle_deg', sa.Float(), nullable=False),
    sa.Column('density_scale', sa.Float(), nullable=False),
    sa.Column('auto_underlay', sa.Boolean(), nullable=False),
    sa.Column('auto_satin', sa.Boolean(), nullable=False),
    sa.Column('max_colors', sa.Integer(), nullable=True),
    sa.Column('engine_version', sa.String(length=20), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('design_id')
    )
    op.create_table('invoices',
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('number', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'paid', 'overdue', 'void', name='invoice_status'), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('line_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'number', name='uq_invoice_number')
    )
    op.create_table('order_events',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('from_status', sa.String(length=30), nullable=True),
    sa.Column('to_status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('design_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('placement', sa.String(length=80), nullable=True),
    sa.Column('pricing_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_order_item_qty'),
    sa.ForeignKeyConstraint(['design_id'], ['designs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_items')
    op.drop_table('order_events')
    op.drop_table('invoices')
    op.drop_table('embroidery_settings')
    op.drop_index('ix_files_design_kind', table_name='design_files')
    op.drop_table('design_files')
    op.drop_index('ix_orders_org_status', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_designs_org_created', table_name='designs')
    op.drop_table('designs')
    op.drop_index('ix_usage_org_period', table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_table('subscriptions')
    op.drop_table('products')
    op.drop_table('memberships')
    op.drop_table('machines')
    op.drop_index('ix_customers_org_name', table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('organizations')
    # ### end Alembic commands ###

    # Autogenerate creates the enum types implicitly but never drops them,
    # which makes a downgrade/upgrade cycle fail on the second CREATE TYPE.
    for enum_name in (
        "design_status",
        "design_source",
        "file_kind",
        "order_status",
        "invoice_status",
        "plan_tier",
        "subscription_status",
        "org_role",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
