"""AI usage ledger and tenant-scoped result cache

Two tables that together make AI spend measurable and repeat spend avoidable.

``ai_call_events`` is the meter: one append-only row per *attempt* to reach a
provider, plus a row for every cache hit, budget block and kill-switch skip. It
holds counts, money and outcomes — never prompt text, artwork or model output.

``ai_result_cache`` is scoped to a workspace by a unique key on
``(organization_id, cache_key)``. Two tenants that upload the same artwork each
keep their own entry; there is no shared bucket to read across.

Written by hand rather than autogenerated: autogenerate wanted to drop the
foreign-key indexes added in b1c2d3e4f5a6, which are declared in SQL rather
than in the model metadata.

Revision ID: c3d4e5f6a7b8
Revises: b1c2d3e4f5a6
Create Date: 2026-08-02
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c3d4e5f6a7b8"
down_revision: Union[str, None] = "b1c2d3e4f5a6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "ai_call_events",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        # Nullable so an unattributed call (a script, a management command) is
        # still metered and still counts against the global budget.
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("operation", sa.String(length=60), nullable=False),
        sa.Column("provider", sa.String(length=30), nullable=True),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("tier", sa.String(length=20), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("outcome", sa.String(length=24), nullable=False),
        sa.Column("reason", sa.String(length=60), nullable=True),
        sa.Column("cache_hit", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("input_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("output_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("cache_read_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("cache_write_tokens", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "tokens_measured", sa.Boolean(), nullable=False, server_default=sa.false()
        ),
        # NULL, never 0, when the model has no configured rate. A zero would
        # understate the real bill and corrupt every average built on it.
        sa.Column("estimated_cost_usd", sa.Numeric(precision=12, scale=8), nullable=True),
        sa.Column("actual_cost_usd", sa.Numeric(precision=12, scale=8), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False, server_default="USD"),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("artwork_hash", sa.String(length=64), nullable=True),
        sa.Column("request_id", sa.String(length=120), nullable=True),
        sa.Column(
            "meta",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default="{}",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ai_calls_org_time", "ai_call_events", ["organization_id", "occurred_at"]
    )
    op.create_index("ix_ai_calls_user_time", "ai_call_events", ["user_id", "occurred_at"])
    op.create_index("ix_ai_calls_time", "ai_call_events", ["occurred_at"])
    op.create_index("ix_ai_calls_operation", "ai_call_events", ["operation", "occurred_at"])
    op.create_index(
        op.f("ix_ai_call_events_artwork_hash"), "ai_call_events", ["artwork_hash"]
    )

    op.create_table(
        "ai_result_cache",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("organization_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("cache_key", sa.String(length=64), nullable=False),
        sa.Column("operation", sa.String(length=60), nullable=False),
        sa.Column("artwork_hash", sa.String(length=64), nullable=False),
        sa.Column("prompt_version", sa.String(length=40), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_hit_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("hit_count", sa.Integer(), nullable=False, server_default="0"),
        sa.ForeignKeyConstraint(
            ["organization_id"], ["organizations.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        # The tenant boundary, enforced by the database rather than by a filter
        # someone might forget to write.
        sa.UniqueConstraint("organization_id", "cache_key", name="uq_ai_cache_tenant_key"),
    )
    op.create_index(
        "ix_ai_cache_org_artwork", "ai_result_cache", ["organization_id", "artwork_hash"]
    )
    op.create_index("ix_ai_cache_expiry", "ai_result_cache", ["expires_at"])


def downgrade() -> None:
    op.drop_index("ix_ai_cache_expiry", table_name="ai_result_cache")
    op.drop_index("ix_ai_cache_org_artwork", table_name="ai_result_cache")
    op.drop_table("ai_result_cache")

    op.drop_index(op.f("ix_ai_call_events_artwork_hash"), table_name="ai_call_events")
    op.drop_index("ix_ai_calls_operation", table_name="ai_call_events")
    op.drop_index("ix_ai_calls_time", table_name="ai_call_events")
    op.drop_index("ix_ai_calls_user_time", table_name="ai_call_events")
    op.drop_index("ix_ai_calls_org_time", table_name="ai_call_events")
    op.drop_table("ai_call_events")
