/**
 * A colour that is used, left, and returned to.
 *
 * Layering forces this: a shape sitting on top of another must sew after it,
 * even when that means going back to a thread already used. The colour block
 * ordinal then stops matching the palette index, and anything that confuses the
 * two will put the wrong thread in the preview and in the exported file.
 */

import { describe, expect, it } from 'vitest';
import { computeStats, type EmbroideryDesign } from '../src/domain/design';
import { BROTHER_SE700 } from '../src/domain/machine';
import { colorBlocks } from '../src/domain/stitch';
import { PEC_THREADS } from '../src/domain/thread';
import { mmToUnits } from '../src/domain/units';
import { defaultUnderlay, type EmbroideryObject } from '../src/domain/embroidery-object';
import { buildStitchSequence } from '../src/domain/stitch-sequence';
import { createProject, regenerate } from '../src/app/pipeline';
import { reorderAndRegenerate } from '../src/app/pipeline';
import { exportPes } from '../src/app/export-pes';
import { readPes } from '../src/infra/pes/pes-reader';

const machine = BROTHER_SE700;
const black = PEC_THREADS.find((t) => t.name === 'Black')!;
const red = PEC_THREADS.find((t) => t.name === 'Red')!;

const square = (x: number, y: number, size: number) => ({
  outer: [
    { x, y },
    { x: x + size, y },
    { x: x + size, y: y + size },
    { x, y: y + size },
  ],
  holes: [],
});

function object(
  id: string,
  threadIndex: number,
  x: number,
  y: number,
  size: number,
  order: number,
): EmbroideryObject {
  return {
    id,
    name: id,
    type: 'fill',
    geometry: { kind: 'polygon', polygon: square(x, y, size) },
    threadIndex,
    angle: 0,
    density: mmToUnits(0.5),
    stitchLength: mmToUnits(3.5),
    underlay: defaultUnderlay('none'),
    order,
    forceTrimBefore: false,
    visible: true,
    notes: [],
    autoGenerated: true,
  };
}

/**
 * A badge: a large black plate, a red panel on top of it, and a small black
 * detail on top of the panel. Black is used, left for red, then returned to.
 */
function layeredDesign(): EmbroideryDesign {
  const { design } = createProject({
    name: 'Layered badge',
    machineId: machine.id,
    hoopId: 'se700-5x7',
    width: mmToUnits(70),
    height: mmToUnits(70),
  });

  const objects = [
    object('plate', 0, mmToUnits(5), mmToUnits(5), mmToUnits(40), 0),
    object('panel', 1, mmToUnits(12), mmToUnits(12), mmToUnits(26), 1),
    object('detail', 0, mmToUnits(20), mmToUnits(20), mmToUnits(10), 2),
  ];

  return regenerate({ ...design, threadPalette: [black, red], objects }, machine);
}

describe('a colour used, left, and returned to', () => {
  it('produces more colour blocks than palette entries', () => {
    const design = reorderAndRegenerate(layeredDesign(), machine);
    const order = design.objects.sort((a, b) => a.order - b.order).map((o) => o.id);
    // Layering must put the detail last, after the panel it sits on.
    expect(order).toEqual(['plate', 'panel', 'detail']);

    const blocks = colorBlocks(design.stitches);
    expect(blocks.length).toBe(3);
    expect(design.threadPalette.length).toBe(2);
    // The block ordinal now exceeds the palette, which is the trap.
    expect(blocks[2].threadIndex).toBe(2);
  });

  it('records which palette entry each colour block actually uses', () => {
    const design = reorderAndRegenerate(layeredDesign(), machine);
    expect(design.colorSequence).toEqual([0, 1, 0]);
  });

  it('resolves the right thread for every block in the stitch sequence', () => {
    const design = reorderAndRegenerate(layeredDesign(), machine);
    const sequence = buildStitchSequence(design);

    expect(sequence.blockThreads.map((t) => t.name)).toEqual(['Black', 'Red', 'Black']);
  });

  it('exports the returned-to colour correctly instead of blocking', () => {
    const design = reorderAndRegenerate(layeredDesign(), machine);
    const result = exportPes(design, machine, { acknowledgeWarnings: true });

    expect(result.blockedReason).toBeUndefined();
    expect(result.ok).toBe(true);

    const back = readPes(result.bytes!);
    expect(back.threads.map((t) => t.name)).toEqual(['Black', 'Red', 'Black']);
  });

  it('reports three colour blocks but two physical thread cones', () => {
    const design = reorderAndRegenerate(layeredDesign(), machine);
    const stats = computeStats(design);
    expect(stats.colorCount).toBe(3);
    expect(stats.colorChangeCount).toBe(2);
    expect(new Set(design.colorSequence).size).toBe(2);
  });
});

describe('stitch sequence identity', () => {
  it('gives the same design the same digest', () => {
    const a = buildStitchSequence(layeredDesign());
    const b = buildStitchSequence(layeredDesign());
    expect(a.id).toBe(b.id);
  });

  it('changes the digest when a thread changes', () => {
    const design = layeredDesign();
    const a = buildStitchSequence(design);
    const b = buildStitchSequence({
      ...design,
      threadPalette: [PEC_THREADS.find((t) => t.name === 'Blue')!, red],
    });
    expect(a.id).not.toBe(b.id);
  });

  it('changes the digest when the stitches change', () => {
    const design = layeredDesign();
    const a = buildStitchSequence(design);
    const b = buildStitchSequence({
      ...design,
      stitches: design.stitches.slice(0, -2),
    });
    expect(a.id).not.toBe(b.id);
  });

  it('is the exact sequence the export encodes', () => {
    const design = reorderAndRegenerate(layeredDesign(), machine);
    const sequence = buildStitchSequence(design);
    const result = exportPes(design, machine, { acknowledgeWarnings: true });

    expect(result.ok).toBe(true);
    // The export records which sequence it encoded, so the preview and the
    // file can be proven to come from the same data.
    expect(result.sequenceId).toBe(sequence.id);
  });
});
