"""Devices, security events, sensors, and the job queue.

Revision ID: 0002_devices_events_sensors_jobs
Revises: 0001_foundation

The observation half of the schema. Three things here are worth reading rather
than skimming, because autogenerate cannot express *why*:

* ``security_events`` carries a BRIN index on ``received_at``. Rows are
  appended in time order, so each 128-page block spans a narrow timestamp
  range; the index stores only those ranges and is kilobytes where a B-tree
  would be hundreds of megabytes at scale.
* ``jobs`` carries a *partial* index covering only ``PENDING`` rows, with a
  column order matching the claim query's ORDER BY exactly. It stays small
  however much completed history accumulates.
* ``uq_jobs_dedupe_key_pending`` is a partial unique index, so at most one
  *pending* job may exist per key, while completed jobs with the same key do
  not block future work.

Downgrade drops in reverse dependency order: security_events references both
devices and sensors, so it goes first.
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0002_devices_events_sensors_jobs"
down_revision: str | None = "0001_foundation"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("mac_address", sa.String(length=17), nullable=True),
        sa.Column("ip_address", postgresql.INET(), nullable=True),
        sa.Column("hostname", sa.String(length=255), nullable=True),
        sa.Column("vendor", sa.String(length=128), nullable=True),
        sa.Column("label", sa.String(length=128), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "tags",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_trusted", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("state", sa.String(length=16), server_default="ACTIVE", nullable=False),
        sa.Column("risk_score", sa.Integer(), nullable=True),
        sa.Column("risk_level", sa.String(length=16), server_default="UNKNOWN", nullable=False),
        sa.Column("risk_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_simulation", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "risk_level IN ('UNKNOWN', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')",
            name=op.f("ck_devices_risk_level_valid"),
        ),
        sa.CheckConstraint(
            "state IN ('ACTIVE', 'IDLE', 'QUARANTINED', 'RETIRED')",
            name=op.f("ck_devices_state_valid"),
        ),
        sa.CheckConstraint(
            "mac_address IS NOT NULL OR ip_address IS NOT NULL",
            name=op.f("ck_devices_identifiable"),
        ),
        sa.CheckConstraint(
            "risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 100)",
            name=op.f("ck_devices_risk_score_range"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_devices")),
        sa.UniqueConstraint("mac_address", name=op.f("uq_devices_mac_address")),
    )
    op.create_index("ix_devices_ip_address", "devices", ["ip_address"], unique=False)
    op.create_index(
        "ix_devices_last_seen_at", "devices", [sa.literal_column("last_seen_at DESC")], unique=False
    )
    # Partial unique index: devices seen only through a router have no MAC, and
    # without this two ingestion workers racing on the same address would create
    # two rows for one host.
    op.create_index(
        "uq_devices_ip_address_when_no_mac",
        "devices",
        ["ip_address"],
        unique=True,
        postgresql_where=sa.text("mac_address IS NULL"),
    )
    op.create_index(
        "ix_devices_risk_score", "devices", [sa.literal_column("risk_score DESC")], unique=False
    )
    op.create_index("ix_devices_state", "devices", ["state"], unique=False)
    op.create_table(
        "sensors",
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("driver", sa.String(length=32), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "config",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), server_default="STOPPED", nullable=False),
        sa.Column("status_detail", sa.String(length=500), nullable=True),
        sa.Column("last_heartbeat_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_event_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.String(length=500), nullable=True),
        sa.Column("events_ingested", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("events_dropped", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("is_simulation", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('STOPPED', 'STARTING', 'RUNNING', 'COMPLETED', 'DEGRADED', 'FAILED', 'NOT_AVAILABLE', 'NOT_CONFIGURED')",
            name=op.f("ck_sensors_status_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sensors")),
        sa.UniqueConstraint("name", name=op.f("uq_sensors_name")),
    )
    op.create_index("ix_sensors_enabled_status", "sensors", ["enabled", "status"], unique=False)
    op.create_table(
        "jobs",
        sa.Column("queue", sa.String(length=32), server_default="default", nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column(
            "payload",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=16), server_default="PENDING", nullable=False),
        sa.Column("priority", sa.SmallInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "run_after", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.Integer(), server_default=sa.text("5"), nullable=False),
        sa.Column("timeout_seconds", sa.Integer(), server_default=sa.text("120"), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("locked_by", sa.String(length=64), nullable=True),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "cancel_requested", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_by_user_id", sa.UUID(), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("dedupe_key", sa.String(length=128), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'DEAD', 'CANCELLED')",
            name=op.f("ck_jobs_status_valid"),
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_jobs_attempts_non_negative")),
        sa.CheckConstraint("max_attempts >= 1", name=op.f("ck_jobs_max_attempts_positive")),
        sa.CheckConstraint("timeout_seconds > 0", name=op.f("ck_jobs_timeout_positive")),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
            name=op.f("fk_jobs_created_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_jobs")),
    )
    op.create_index(
        "ix_jobs_claim",
        "jobs",
        ["queue", sa.literal_column("priority DESC"), "run_after"],
        unique=False,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_index(
        "ix_jobs_running_locked_at",
        "jobs",
        ["locked_at"],
        unique=False,
        postgresql_where=sa.text("status = 'RUNNING'"),
    )
    op.create_index("ix_jobs_status_created_at", "jobs", ["status", "created_at"], unique=False)
    op.create_index(
        "uq_jobs_dedupe_key_pending",
        "jobs",
        ["dedupe_key"],
        unique=True,
        postgresql_where=sa.text("status = 'PENDING' AND dedupe_key IS NOT NULL"),
    )
    op.create_table(
        "security_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("event_uid", sa.UUID(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("sensor_id", sa.UUID(), nullable=True),
        sa.Column("sensor_name", sa.String(length=64), nullable=False),
        sa.Column("driver", sa.String(length=32), nullable=False),
        sa.Column("category", sa.String(length=16), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("severity", sa.String(length=16), server_default="INFO", nullable=False),
        sa.Column("confidence", sa.SmallInteger(), server_default=sa.text("100"), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=True),
        sa.Column("source_ip", postgresql.INET(), nullable=True),
        sa.Column("destination_ip", postgresql.INET(), nullable=True),
        sa.Column("source_port", sa.Integer(), nullable=True),
        sa.Column("destination_port", sa.Integer(), nullable=True),
        sa.Column("protocol", sa.String(length=16), nullable=True),
        sa.Column("mac_address", sa.String(length=17), nullable=True),
        sa.Column("summary", sa.String(length=500), nullable=False),
        sa.Column(
            "attributes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("raw", sa.Text(), nullable=True),
        sa.Column("is_simulation", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.CheckConstraint(
            "category IN ('DISCOVERY', 'TRAFFIC', 'LOG', 'SCAN', 'AUTH', 'ANOMALY', 'SYSTEM')",
            name=op.f("ck_security_events_category_valid"),
        ),
        sa.CheckConstraint(
            "severity IN ('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')",
            name=op.f("ck_security_events_severity_valid"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 100",
            name=op.f("ck_security_events_confidence_range"),
        ),
        sa.CheckConstraint(
            "destination_port IS NULL OR (destination_port >= 0 AND destination_port <= 65535)",
            name=op.f("ck_security_events_destination_port_range"),
        ),
        sa.CheckConstraint(
            "source_port IS NULL OR (source_port >= 0 AND source_port <= 65535)",
            name=op.f("ck_security_events_source_port_range"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_security_events_device_id_devices"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["sensor_id"],
            ["sensors.id"],
            name=op.f("fk_security_events_sensor_id_sensors"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_security_events")),
        sa.UniqueConstraint("event_uid", name=op.f("uq_security_events_event_uid")),
    )
    op.create_index(
        "ix_security_events_attributes",
        "security_events",
        ["attributes"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"attributes": "jsonb_path_ops"},
    )
    op.create_index(
        "ix_security_events_category_occurred_at",
        "security_events",
        ["category", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_security_events_destination_ip", "security_events", ["destination_ip"], unique=False
    )
    op.create_index(
        "ix_security_events_device_id_occurred_at",
        "security_events",
        ["device_id", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_security_events_occurred_at",
        "security_events",
        [sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_security_events_real_occurred_at",
        "security_events",
        [sa.literal_column("occurred_at DESC")],
        unique=False,
        postgresql_where=sa.text("is_simulation = false"),
    )
    op.create_index(
        "ix_security_events_received_at_brin",
        "security_events",
        ["received_at"],
        unique=False,
        postgresql_using="brin",
        postgresql_with={"pages_per_range": 128},
    )
    op.create_index(
        "ix_security_events_severity_occurred_at",
        "security_events",
        ["severity", sa.literal_column("occurred_at DESC")],
        unique=False,
    )
    op.create_index("ix_security_events_source_ip", "security_events", ["source_ip"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_security_events_source_ip", table_name="security_events")
    op.drop_index("ix_security_events_severity_occurred_at", table_name="security_events")
    op.drop_index(
        "ix_security_events_received_at_brin",
        table_name="security_events",
        postgresql_using="brin",
        postgresql_with={"pages_per_range": 128},
    )
    op.drop_index(
        "ix_security_events_real_occurred_at",
        table_name="security_events",
        postgresql_where=sa.text("is_simulation = false"),
    )
    op.drop_index("ix_security_events_occurred_at", table_name="security_events")
    op.drop_index("ix_security_events_device_id_occurred_at", table_name="security_events")
    op.drop_index("ix_security_events_destination_ip", table_name="security_events")
    op.drop_index("ix_security_events_category_occurred_at", table_name="security_events")
    op.drop_index(
        "ix_security_events_attributes",
        table_name="security_events",
        postgresql_using="gin",
        postgresql_ops={"attributes": "jsonb_path_ops"},
    )
    op.drop_table("security_events")
    op.drop_index(
        "uq_jobs_dedupe_key_pending",
        table_name="jobs",
        postgresql_where=sa.text("status = 'PENDING' AND dedupe_key IS NOT NULL"),
    )
    op.drop_index("ix_jobs_status_created_at", table_name="jobs")
    op.drop_index(
        "ix_jobs_running_locked_at",
        table_name="jobs",
        postgresql_where=sa.text("status = 'RUNNING'"),
    )
    op.drop_index(
        "ix_jobs_claim", table_name="jobs", postgresql_where=sa.text("status = 'PENDING'")
    )
    op.drop_table("jobs")
    op.drop_index("ix_sensors_enabled_status", table_name="sensors")
    op.drop_table("sensors")
    op.drop_index("ix_devices_state", table_name="devices")
    op.drop_index("ix_devices_risk_score", table_name="devices")
    op.drop_index("uq_devices_ip_address_when_no_mac", table_name="devices")
    op.drop_index("ix_devices_last_seen_at", table_name="devices")
    op.drop_index("ix_devices_ip_address", table_name="devices")
    op.drop_table("devices")
    # ### end Alembic commands ###
