"""Findings, their evidence links, device risk assessments, and the watermark.

Revision ID: 0003_findings_risk
Revises: 0002_devices_events_sensors_jobs

The detection half of the schema. Four constraints here carry the milestone's
correctness guarantees and are not incidental:

* ``uq_findings_fingerprint`` — one row per thing detected. Analysis is replayed
  whenever a job is redelivered, and this is what makes replay produce an update
  instead of a duplicate. An application-level existence check cannot do this:
  between its SELECT and its INSERT, a concurrent worker commits.
* ``pk_finding_observations (finding_id, event_id)`` — one observation supports
  one finding at most once, so ``findings.observation_count`` and every risk
  factor derived from evidence are safe under retry.
* ``ON DELETE CASCADE`` from ``security_events`` to ``finding_observations`` —
  retention prunes events, and a dangling evidence link would let the API claim
  evidence it can no longer produce. The finding keeps a bounded snapshot in
  ``evidence`` and reports the difference honestly.
* ``ck_findings_observation_window_ordered`` — ``last_observed_at`` can never
  precede ``first_observed_at``, which is otherwise easy to violate when an
  out-of-order batch widens the window.

``findings.confidence`` and ``findings.severity`` are separate columns with
separate constraints, deliberately: they answer different questions and a HIGH
severity / LOW confidence finding must be representable.

Downgrade drops in reverse dependency order: ``finding_observations`` references
both ``findings`` and ``security_events``, so it goes first.
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = "0003_findings_risk"
down_revision: str | None = "0002_devices_events_sensors_jobs"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "detection_state",
        sa.Column("stream", sa.String(length=32), nullable=False),
        sa.Column("last_event_id", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_run_status", sa.String(length=16), nullable=True),
        sa.Column("events_examined", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("findings_created", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column("findings_updated", sa.BigInteger(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "last_run_status IS NULL OR last_run_status IN ('SUCCEEDED', 'FAILED')",
            name=op.f("ck_detection_state_last_run_status_valid"),
        ),
        sa.CheckConstraint(
            "last_event_id >= 0", name=op.f("ck_detection_state_last_event_id_non_negative")
        ),
        sa.PrimaryKeyConstraint("stream", name=op.f("pk_detection_state")),
    )
    op.create_table(
        "device_risk_assessments",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=False),
        sa.Column(
            "assessed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("previous_score", sa.Integer(), nullable=True),
        sa.Column("previous_level", sa.String(length=16), nullable=True),
        sa.Column(
            "factors",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "contributing_finding_ids",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("window_started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("window_ended_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("weights_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("is_simulation", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.CheckConstraint(
            "level IN ('UNKNOWN', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')",
            name=op.f("ck_device_risk_assessments_level_valid"),
        ),
        sa.CheckConstraint(
            "score >= 0 AND score <= 100", name=op.f("ck_device_risk_assessments_score_range")
        ),
        sa.CheckConstraint(
            "window_ended_at >= window_started_at",
            name=op.f("ck_device_risk_assessments_window_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_device_risk_assessments_device_id_devices"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device_risk_assessments")),
    )
    op.create_index(
        "ix_device_risk_assessments_device_id_assessed_at",
        "device_risk_assessments",
        ["device_id", sa.literal_column("assessed_at DESC")],
        unique=False,
    )
    op.create_table(
        "findings",
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("detector", sa.String(length=64), nullable=False),
        sa.Column("rule_version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("detection_type", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.SmallInteger(), nullable=False),
        sa.Column("risk_score", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=16), server_default="OPEN", nullable=False),
        sa.Column("first_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("device_id", sa.UUID(), nullable=True),
        sa.Column("observation_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "evidence",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column(
            "risk_factors",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("is_simulation", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("triaged_by_user_id", sa.UUID(), nullable=True),
        sa.Column("triaged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("triage_note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "detection_type IN ('NEW_DEVICE', 'IDENTITY_CHANGE', 'REPEATED_ANOMALY', 'UNEXPECTED_COMMUNICATION')",
            name=op.f("ck_findings_detection_type_valid"),
        ),
        sa.CheckConstraint(
            "severity IN ('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')",
            name=op.f("ck_findings_severity_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'SUPPRESSED', 'FALSE_POSITIVE')",
            name=op.f("ck_findings_status_valid"),
        ),
        sa.CheckConstraint(
            "confidence >= 0 AND confidence <= 100", name=op.f("ck_findings_confidence_range")
        ),
        sa.CheckConstraint(
            "last_observed_at >= first_observed_at",
            name=op.f("ck_findings_observation_window_ordered"),
        ),
        sa.CheckConstraint(
            "observation_count >= 0", name=op.f("ck_findings_observation_count_non_negative")
        ),
        sa.CheckConstraint(
            "risk_score IS NULL OR (risk_score >= 0 AND risk_score <= 100)",
            name=op.f("ck_findings_risk_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["devices.id"],
            name=op.f("fk_findings_device_id_devices"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["triaged_by_user_id"],
            ["users.id"],
            name=op.f("fk_findings_triaged_by_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
        sa.UniqueConstraint("fingerprint", name=op.f("uq_findings_fingerprint")),
    )
    op.create_index("ix_findings_detection_type", "findings", ["detection_type"], unique=False)
    op.create_index("ix_findings_detector", "findings", ["detector"], unique=False)
    op.create_index(
        "ix_findings_device_id_last_observed_at",
        "findings",
        ["device_id", sa.literal_column("last_observed_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_findings_open_risk_score",
        "findings",
        [sa.literal_column("risk_score DESC")],
        unique=False,
        postgresql_where=sa.text("status IN ('OPEN', 'ACKNOWLEDGED')"),
    )
    op.create_index(
        "ix_findings_real_last_observed_at",
        "findings",
        [sa.literal_column("last_observed_at DESC")],
        unique=False,
        postgresql_where=sa.text("is_simulation = false"),
    )
    op.create_index(
        "ix_findings_status_last_observed_at",
        "findings",
        ["status", sa.literal_column("last_observed_at DESC")],
        unique=False,
    )
    op.create_table(
        "finding_observations",
        sa.Column("finding_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.Column("role", sa.String(length=16), server_default="SUPPORTING", nullable=False),
        sa.Column(
            "linked_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "role IN ('TRIGGER', 'SUPPORTING', 'BASELINE')",
            name=op.f("ck_finding_observations_role_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["security_events.id"],
            name=op.f("fk_finding_observations_event_id_security_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.id"],
            name=op.f("fk_finding_observations_finding_id_findings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("finding_id", "event_id", name=op.f("pk_finding_observations")),
    )
    op.create_index(
        "ix_finding_observations_event_id", "finding_observations", ["event_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_finding_observations_event_id", table_name="finding_observations")
    op.drop_table("finding_observations")
    op.drop_index("ix_findings_status_last_observed_at", table_name="findings")
    op.drop_index(
        "ix_findings_real_last_observed_at",
        table_name="findings",
        postgresql_where=sa.text("is_simulation = false"),
    )
    op.drop_index(
        "ix_findings_open_risk_score",
        table_name="findings",
        postgresql_where=sa.text("status IN ('OPEN', 'ACKNOWLEDGED')"),
    )
    op.drop_index("ix_findings_device_id_last_observed_at", table_name="findings")
    op.drop_index("ix_findings_detector", table_name="findings")
    op.drop_index("ix_findings_detection_type", table_name="findings")
    op.drop_table("findings")
    op.drop_index(
        "ix_device_risk_assessments_device_id_assessed_at", table_name="device_risk_assessments"
    )
    op.drop_table("device_risk_assessments")
    op.drop_table("detection_state")
    # ### end Alembic commands ###
