"""Declarative base, naming conventions, and shared column mixins.

Naming conventions
------------------
PostgreSQL will happily invent a name for an unnamed constraint
(``devices_ip_key``, ``ck_events_1a2b``). Those names differ between databases
created at different times, and Alembic then generates migrations that try to
drop constraints that do not exist under that name. Declaring a convention up
front makes every constraint name a deterministic function of the table and
columns, so migrations are reproducible and a downgrade can find what an
upgrade created.

Primary key strategy
--------------------
Two kinds of table, two kinds of key:

* **Entities** (users, devices, rules, sensors) use UUIDv4. They appear in URLs
  and in the UI; sequential integers there would let any authenticated viewer
  learn how many users exist and probe for objects by counting.
* **Append-only firehose tables** (events, audit log) use ``BIGINT
  GENERATED ALWAYS AS IDENTITY``. Random UUIDs scatter inserts across a B-tree,
  which dirties many pages per insert and bloats the index; a monotonic key
  appends to the right-hand edge, which is what a table taking thousands of
  rows a minute needs. The audit log additionally *requires* a total order
  because its tamper-evidence is a hash chain over consecutive rows.

The tradeoff is that event ids are guessable. That is acceptable: reading any
event requires an authenticated session with the right role, and the ids carry
no meaning outside the deployment.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime

from sqlalchemy import DateTime, MetaData, func
from sqlalchemy.dialects.postgresql import UUID as PgUUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# %(column_0_N_name)s truncates long multi-column names so generated identifiers
# stay under PostgreSQL's 63-byte limit instead of being silently cut.
NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}

metadata = MetaData(naming_convention=NAMING_CONVENTION)


class Base(DeclarativeBase):
    """Root of the ORM hierarchy.

    Alembic discovers every table through ``Base.metadata``, which is why every
    model module must be imported before autogenerate runs — see
    ``nexus/db/models/__init__.py``.
    """

    metadata = metadata


def utcnow() -> datetime:
    """Timezone-aware current time.

    ``datetime.utcnow()`` returns a *naive* datetime that claims to be local
    time, and comparing it against a timezone-aware value from the database
    raises at runtime. Every timestamp in NEXUS is aware and in UTC; the
    frontend converts to the viewer's zone for display only.
    """
    return datetime.now(UTC)


class UUIDPrimaryKeyMixin:
    """UUIDv4 primary key generated by the application.

    Generated in Python rather than by ``gen_random_uuid()`` so the id is known
    before the INSERT. That lets a service build a whole object graph — a
    device, its first event, an audit entry referencing both — and flush once,
    instead of round-tripping to the database for each generated key.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        PgUUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )


class TimestampMixin:
    """``created_at`` / ``updated_at`` maintained by the database.

    ``server_default=now()`` and ``onupdate`` are set on the server side so a
    row written by a migration, a psql session, or a future non-Python client
    still gets correct timestamps. Trusting the application to set them means
    the one path that forgets produces a NULL you discover during an incident.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
