/**
 * An EmbroideryObject is the editable unit of a design: a piece of geometry plus
 * the parameters that say how it should be stitched. Stitches are always
 * regenerated from objects, never edited directly, so an edit anywhere in the
 * design stays consistent with the exported file.
 */

import type { Point, Polygon } from './geometry';

export type StitchType =
  | 'fill'
  | 'satin'
  | 'running'
  | 'bean'
  | 'outline'
  | 'manual';

export type UnderlayType = 'none' | 'edge-run' | 'zigzag' | 'center-run' | 'full';

export interface UnderlaySettings {
  type: UnderlayType;
  /** Inset of the underlay from the object edge, 0.1 mm units. */
  inset: number;
  /** Spacing for zigzag / parallel underlay, 0.1 mm units. */
  spacing: number;
  /** Stitch length used for underlay, 0.1 mm units. */
  stitchLength: number;
}

export const defaultUnderlay = (type: UnderlayType): UnderlaySettings => ({
  type,
  inset: 8,
  spacing: 25,
  stitchLength: 25,
});

/** Geometry payload; the shape depends on the stitch type. */
export type ObjectGeometry =
  | { kind: 'polygon'; polygon: Polygon }
  /** Two rails of a satin column, walked in the same direction. */
  | { kind: 'column'; left: Point[]; right: Point[] }
  | { kind: 'path'; points: Point[]; closed: boolean };

export interface EmbroideryObject {
  id: string;
  name: string;
  type: StitchType;
  geometry: ObjectGeometry;
  /** Index into the design's thread palette. */
  threadIndex: number;
  /** Fill angle in degrees; 0 = horizontal rows. Ignored by running stitch. */
  angle: number;
  /** Distance between fill rows / satin stitches, 0.1 mm units. */
  density: number;
  /** Maximum stitch length, 0.1 mm units. */
  stitchLength: number;
  /** Satin/column width override for path-based satin, 0.1 mm units. */
  columnWidth?: number;
  /** Number of passes for bean stitch (3 = triple). */
  beanRepeats?: number;
  underlay: UnderlaySettings;
  /** Order in the sew sequence. Lower sews first. */
  order: number;
  /** Force a trim before this object even if the travel distance is short. */
  forceTrimBefore: boolean;
  visible: boolean;
  /** Set when automatic digitizing was unsure about this object. */
  notes: string[];
  /** True when the object came from automatic digitization (vs. user edit). */
  autoGenerated: boolean;
}

export const DEFAULTS = {
  fillDensity: 4, // 0.4 mm between rows
  fillStitchLength: 35, // 3.5 mm
  satinDensity: 4, // 0.4 mm between needle penetrations
  runningStitchLength: 20, // 2.0 mm
  maxStitchLength: 120, // 12 mm
  minStitchLength: 6, // 0.6 mm — shorter than this risks thread breaks
  /** Widest column still sewn as satin, 0.1 mm units (10 mm). */
  satinMaxWidth: 100,
  /** Narrowest column that is reliable as satin (1.0 mm). */
  satinMinWidth: 10,
  /** Below this width a region becomes a running-stitch line (0.9 mm). */
  runningMaxWidth: 9,
} as const;

export function objectPoints(obj: EmbroideryObject): Point[] {
  switch (obj.geometry.kind) {
    case 'polygon':
      return [...obj.geometry.polygon.outer, ...obj.geometry.polygon.holes.flat()];
    case 'column':
      return [...obj.geometry.left, ...obj.geometry.right];
    case 'path':
      return obj.geometry.points;
  }
}

export function mapGeometry(
  geometry: ObjectGeometry,
  fn: (p: Point) => Point,
): ObjectGeometry {
  switch (geometry.kind) {
    case 'polygon':
      return {
        kind: 'polygon',
        polygon: {
          outer: geometry.polygon.outer.map(fn),
          holes: geometry.polygon.holes.map((h) => h.map(fn)),
        },
      };
    case 'column':
      return { kind: 'column', left: geometry.left.map(fn), right: geometry.right.map(fn) };
    case 'path':
      return { kind: 'path', points: geometry.points.map(fn), closed: geometry.closed };
  }
}

export function cloneObject(obj: EmbroideryObject, id: string): EmbroideryObject {
  return {
    ...obj,
    id,
    name: `${obj.name} copy`,
    geometry: mapGeometry(obj.geometry, (p) => ({ ...p })),
    underlay: { ...obj.underlay },
    notes: [...obj.notes],
  };
}
